### ISSUE TITLE
unable to run sippy_cup scenario (CentOS Linux release 7.2.1511 (Core))

### ISSUE THREAD

**Issue by vijayaa** [mojolingo/sippy_cup#93] opened 2017-03-15 09:17 UTC
**i have run sippy_cup -r simple_call.yml. It is throwing the following error**

`/usr/local/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node.rb:390: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/lib/sippy_cup/media.rb:117:in `new_packet': uninitialized constant PacketFu::UDPPacket (NameError)
Did you mean?  PacketFu::Packet
               Packet
               UDPSocket
        from /usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/lib/sippy_cup/media.rb:49:in `block (2 levels) in compile!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/lib/sippy_cup/media.rb:48:in `times'
        from /usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/lib/sippy_cup/media.rb:48:in `block in compile!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/lib/sippy_cup/media.rb:41:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/lib/sippy_cup/media.rb:41:in `compile!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/lib/sippy_cup/scenario.rb:792:in `compile_media'
        from /usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/lib/sippy_cup/scenario.rb:726:in `to_tmpfiles'
        from /usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/lib/sippy_cup/runner.rb:36:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/sippy_cup-0.7.2/bin/sippy_cup:75:in `<top (required)>'
        from /usr/local/bin/sippy_cup:22:in `load'
        from /usr/local/bin/sippy_cup:22:in `<main>' `

**Comment by bklang** [comment] 2017-03-15 13:58
This is a duplicate of #91, which was solved in #92.  We will make a new release of sippy_cup to Rubygems, but in the meantime you can check out the code to get the fix.

**Closed as completed by bklang** 2017-03-15 13:58 UTC

**Comment by vijayaa** [comment] 2017-03-16 06:53
thanks @bklang for you help.it worked
